### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 15: character maps to <undefined>

### ISSUE THREAD

**Issue by Deathnerd** [JackofSpades707/instant_torrent#1]
Fresh install under Python 3.5 running on Windows 10. 32 bit Python.

![Screenshot](https://cloud.githubusercontent.com/assets/1685953/19153674/76922a36-8ba5-11e6-8590-a6de19929cdf.PNG)

**Comment by JackofSpades707** [comment]
could you please run 'pip list' and post the output here? I'll try to replicate this and address the issue

**Comment by JackofSpades707** [comment]
Fixed with newest release, preview : http://i.imgur.com/YCgUtxj.png
You can uninstall the current version via 'pip uninstall instanttorrent'
and then reinstall the latest version via 'pip install instanttorrent' :)
